### ISSUE TITLE
Large number of variants are incorrectly mapped

### ISSUE THREAD

**Issue by marikaris** [molgenis/data-transform-vkgl#14]
Input: 
`NM_000702.2:c.2841-19delTinsCT chr1 160109411 T > CT`

Observed:
`chr1 160109412 C > CT`

Expected:
`chr1 160109411 T > CT`

**Comment by dennishendriksen** [comment]
I can't reproduce the issue:

`curl -i -H 'Content-Type: application/json' -d '["NM_000702.2:c.2841-19delTinsCT"]' <url>/h2v`

gives:
```
HTTP/1.1 200 OK
Server: nginx/1.17.10
Date:<cut>
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: <cut>

[{"error": "Cannot validate sequence of an intronic variant (NM_000702.2:c.2841-19delinsCT)"}]
```
which seems like a different error.
